services:
  db-dev:
    image: postgres:16.0
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    restart: always

  backend-dev:
    build: .
    restart: always
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...'
        sleep 10
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db-dev

volumes:
    postgres_data_dev: